SUPABASE_URL = "https://ttfniigigoiybkflwshi.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0Zm5paWdpZ29peWJrZmx3c2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2OTQwNzQsImV4cCI6MjA4MDI3MDA3NH0.99ePn1oHKp6SryOECz10bKOQgPBom6niJ9vGaqGv2TY"
